version: '3.3'

services:
  web:
    expose:
       - "8000"
    ports:
      - '127.0.0.1:8000:8000'
    image: tsvetovpavel/chat_take_aiohttp

    command: 'chat_take_aiohttp serve'

    depends_on:
      - postgres
      - redis
    links:
      - postgres:postgres
      - redis:redis

#    network_mode: host

  postgres:
    container_name: 'postgres'
    image: tsvetovpavel/postgress
    ports:
      - '127.0.0.1:5432:5432'

  redis:
    container_name: 'redis'
    image: 'redis:3.2.0'
    ports:
      - '127.0.0.1:6379:6379'
